version: "3"

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
    - database-data:/var/lib/postgresql/data/

  django:
    build: .
    image: "django"
    command: ./manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
      - database


volumes:
  database-data: