# Generated by Django 2.2.10 on 2021-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='question', to='interview.Variant', verbose_name='Варианты'),
        ),
    ]
