# Generated by Django 2.2.10 on 2021-06-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_quiz_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
