# Generated by Django 2.2.10 on 2021-07-15 16:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_useranswer_userquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='variants',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquiz',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='interview.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(editable=False, verbose_name='Дата старта'),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
