# Generated by Django 2.2.10 on 2021-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_auto_20210715_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата старта'),
        ),
    ]
