# Generated by Django 2.2.10 on 2021-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_remove_variant_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='user_ident',
            field=models.IntegerField(default=1, verbose_name='Идентификатор пользователя'),
            preserve_default=False,
        ),
    ]
