# Generated by Django 2.2.10 on 2021-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_userquiz_user_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='user_ident',
            field=models.IntegerField(unique=True, verbose_name='Идентификатор пользователя'),
        ),
    ]
